cat("WebGet\n")
url <- readline(prompt="Enter URL to WebGet: ")
path <- readline(prompt="\nEnter path to WebGet to (plus extension of file from Web): ")
cat("Getting " url"...")
download.file(url, destfile)
